name: build and test
on: [push]
jobs:
  just_test:
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: go test
        run: go test -v ./...
  test_build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Get the version
        id: get_tag
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: go test
        run: go test -v ./...
      - name: build
        shell: bash
        run: |
          #!/bin/bash
          # Make an artifacts directory
          set -e

          ARTIFACTS_DIR="./artifacts"
          NAME=are_we_there_yet
          VERSION=${{ steps.get_tag.outputs.SOURCE_TAG }}
          BUILD_CMD="go build -a -ldflags=\"-X main.version=$VERSION\""

          mkdir -p $ARTIFACTS_DIR

          # run the build for each supported OS
          for os in "linux" "darwin" "windows"; do
            bin_name="${NAME}_${os}_amd64"
            output="${ARTIFACTS_DIR}/${bin_name}"

            echo "Building for $bin_name ..."
            /bin/bash -c "GOOS=$os GOARCH=amd64 CGO_ENABLED=0 $BUILD_CMD -o $output ."
            
            # If its windows we need to rename it to have .exe at the end.
            if [ $os == "windows" ]; then
                mv "$output" "${output}.exe"
            fi
          done

          # Make an ARM bin for linux also
          for arch in arm64 arm; do
            bin_name="${NAME}_linux_${arch}"
            output="${ARTIFACTS_DIR}/${bin_name}"

            echo "Building for $bin_name ..."
            /bin/bash -c "GOOS=linux GOARCH=$arch CGO_ENABLED=0 $BUILD_CMD -o $output ."
          done

          # Build for Mac with Apple Chips
          for arch in arm64; do
            bin_name="${NAME}_darwin_${arch}"
            output="${ARTIFACTS_DIR}/${bin_name}"

            echo "Building for $bin_name ..."
            /bin/bash -c "GOOS=darwin GOARCH=$arch CGO_ENABLED=0 $BUILD_CMD -o $output ."
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          body_path: .github/workflows/release_body.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
